"use server";

import { revalidatePath } from "next/cache";
import { getSession } from "@/lib/auth";
import { createClient, createAdminClient } from "@/utils/supabase/server";
import { 
  getPostById, 
  createPost, 
  updatePost, 
  deletePost, 
  BlogPost, 
  User,
  updateSystemSettings
} from "@/lib/db";

// Helper to generate a slug from a title
function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// 1. Auth Actions
export async function loginAction(prevState: any, formData: FormData) {
  const username = formData.get("username")?.toString().trim().toLowerCase();
  const password = formData.get("password")?.toString();

  if (!username || !password) {
    return { error: "Please enter both username and password." };
  }

  try {
    const supabase = await createClient();
    const email = `${username}@cosmos.local`;
    
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (error) {
      // Slow down failed authentication to mitigate brute-force attempts
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return { error: "Invalid username or password." };
    }

    return { success: true };
  } catch (err) {
    console.error("Login action error:", err);
    return { error: "An unexpected error occurred during login." };
  }
}

export async function logoutAction() {
  try {
    const supabase = await createClient();
    const { error } = await supabase.auth.signOut();
    if (error) {
      return { error: error.message };
    }
    return { success: true };
  } catch (err) {
    console.error("Logout action error:", err);
    return { error: "An unexpected error occurred during logout." };
  }
}

export async function changePasswordAction(prevState: any, formData: FormData) {
  const session = await getSession();
  if (!session) return { error: "Unauthorized." };

  const newPassword = formData.get("newPassword")?.toString();

  if (!newPassword || newPassword.length < 6) {
    return { error: "Password must be at least 6 characters." };
  }

  try {
    const supabase = await createClient();
    const { error } = await supabase.auth.updateUser({ password: newPassword });

    if (error) {
      return { error: error.message };
    }

    return { success: true, message: "Password updated successfully!" };
  } catch (err) {
    console.error("Change password action error:", err);
    return { error: "Failed to update password." };
  }
}

// 2. Blog Management Actions (Admin & Writer role)
export async function savePostAction(prevState: any, formData: FormData) {
  const session = await getSession();
  if (!session) return { error: "Unauthorized." };

  const id = formData.get("id")?.toString();
  const title = formData.get("title")?.toString().trim();
  const excerpt = formData.get("excerpt")?.toString().trim();
  const content = formData.get("content")?.toString();
  const published = formData.get("published") === "true";
  const coverImage = formData.get("coverImage")?.toString() || "/images/galaxy.jpg";

  if (!title || !content || !excerpt) {
    return { error: "Please fill in Title, Excerpt, and Content." };
  }

  const slug = slugify(title);

  try {
    if (id) {
      // Edit Post
      const existing = await getPostById(id);
      if (!existing) return { error: "Post not found." };

      // Writers can only edit their own posts, unless they are admin
      if (session.role !== "admin" && existing.authorId !== session.userId) {
        return { error: "You can only edit your own posts." };
      }

      const updatedPost: BlogPost = {
        ...existing,
        title,
        slug,
        excerpt,
        content,
        published,
        coverImage,
        updatedAt: new Date().toISOString(),
      };

      await updatePost(updatedPost);
      revalidatePath("/blog");
      revalidatePath(`/blog/${slug}`);
      return { success: true, message: "Post updated successfully!" };
    } else {
      // Create Post
      const newPost: BlogPost = {
        id: "", // uuid will be generated by postgres automatically
        title,
        slug,
        excerpt,
        content,
        coverImage,
        authorId: session.userId,
        authorName: session.name,
        authorRole: session.role,
        published,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      await createPost(newPost);
      revalidatePath("/blog");
      revalidatePath(`/blog/${slug}`);
      return { success: true, message: "Post created successfully!" };
    }
  } catch (err: any) {
    console.error("Save post action error:", err);
    return { error: err.message || "Failed to save post." };
  }
}

export async function deletePostAction(id: string) {
  const session = await getSession();
  if (!session) return { error: "Unauthorized." };

  try {
    const existing = await getPostById(id);
    if (!existing) return { error: "Post not found." };

    if (session.role !== "admin" && existing.authorId !== session.userId) {
      return { error: "You are not authorized to delete this post." };
    }

    await deletePost(id);
    revalidatePath("/blog");
    return { success: true };
  } catch (err: any) {
    console.error("Delete post action error:", err);
    return { error: err.message || "Failed to delete post." };
  }
}

// 3. User Management Actions (Admin only)
export async function saveUserAction(prevState: any, formData: FormData) {
  const session = await getSession();
  if (!session || session.role !== "admin") {
    return { error: "Unauthorized. Admin privileges required." };
  }

  const id = formData.get("id")?.toString();
  const username = formData.get("username")?.toString().trim().toLowerCase();
  const name = formData.get("name")?.toString().trim();
  const role = formData.get("role")?.toString() as "admin" | "writer";
  const password = formData.get("password")?.toString();

  if (!name || !username || !role) {
    return { error: "Please fill in name, username, and role." };
  }

  try {
    const adminSupabase = await createAdminClient();

    if (id) {
      // Edit User
      // 1. Update auth.users email and metadata
      const email = `${username}@cosmos.local`;
      const updateData: any = {
        email,
        email_confirm: true,
        user_metadata: { name, role, username }
      };

      if (password && password.trim() !== "") {
        if (password.length < 6) return { error: "Password must be at least 6 characters." };
        updateData.password = password;
      }

      const { error: authError } = await adminSupabase.auth.admin.updateUserById(id, updateData);
      if (authError) {
        return { error: authError.message };
      }

      // 2. Update public.profiles details
      const { error: profileError } = await adminSupabase
        .from("profiles")
        .update({ name, role, username })
        .eq("id", id);

      if (profileError) {
        return { error: profileError.message };
      }

      return { success: true, message: "User updated successfully!" };
    } else {
      // Create User in Supabase Auth using admin API
      if (!password) return { error: "Password is required for new users." };
      if (password.length < 6) return { error: "Password must be at least 6 characters." };

      const email = `${username}@cosmos.local`;

      const { data: newUser, error: authError } = await adminSupabase.auth.admin.createUser({
        email,
        password,
        email_confirm: true,
        user_metadata: { name, role, username }, // Automatically copied to public.profiles by database trigger
      });

      if (authError) {
        return { error: authError.message };
      }

      return { success: true, message: "User created successfully!" };
    }
  } catch (err: any) {
    console.error("Save user action error:", err);
    return { error: err.message || "Failed to save user." };
  }
}

export async function deleteUserAction(id: string) {
  const session = await getSession();
  if (!session || session.role !== "admin") {
    return { error: "Unauthorized." };
  }

  if (session.userId === id) {
    return { error: "You cannot delete your own admin account." };
  }

  try {
    const adminSupabase = await createAdminClient();
    
    // Deleting the user from auth.users cascade-deletes public.profiles automatically due to foreign key constraints
    const { error } = await adminSupabase.auth.admin.deleteUser(id);

    if (error) {
      return { error: error.message };
    }

    return { success: true };
  } catch (err: any) {
    console.error("Delete user action error:", err);
    return { error: err.message || "Failed to delete user." };
  }
}

// 4. Quick Post Actions
export async function togglePostStatusAction(id: string) {
  const session = await getSession();
  if (!session || session.role !== "admin") {
    return { error: "Unauthorized. Admin privileges required." };
  }

  try {
    const post = await getPostById(id);
    if (!post) return { error: "Post not found." };

    const updatedPost = {
      ...post,
      published: !post.published,
      updatedAt: new Date().toISOString()
    };

    await updatePost(updatedPost);
    revalidatePath("/blog");
    revalidatePath(`/blog/${post.slug}`);
    return { success: true, published: updatedPost.published };
  } catch (err: any) {
    console.error("Toggle post status error:", err);
    return { error: err.message || "Failed to toggle status." };
  }
}

// 5. System Settings Actions
export async function saveSettingsAction(prevState: any, formData: FormData) {
  const session = await getSession();
  if (!session || session.role !== "admin") {
    return { error: "Unauthorized. Admin privileges required." };
  }

  const siteName = formData.get("siteName")?.toString().trim() || "COSMOS";
  const siteDescription = formData.get("siteDescription")?.toString().trim() || "";
  const allowSignups = formData.get("allowSignups") === "true";

  try {
    await updateSystemSettings({ siteName, siteDescription, allowSignups });
    revalidatePath("/");
    revalidatePath("/blog");
    return { success: true, message: "Settings updated successfully!" };
  } catch (err: any) {
    console.error("Save settings action error:", err);
    return { error: err.message || "Failed to save settings." };
  }
}
